### ISSUE TITLE
sonata + translate select + locale

### ISSUE THREAD

**Issue by ibasaw** [a2lix/I18nDoctrineBundle#25]
![translate](https://cloud.githubusercontent.com/assets/313704/12201869/f2838e48-b5fc-11e5-8931-e5dbb91938ba.jpg)

my locale is set to 'fr', got a translation for the field, but this is always english text in hypothesis select

i use sonata admin + this bundle + TranslationFormBundle

here the method

```
  public function __toString(){
    return ($translation = $this->getCurrentTranslation()) ? $translation->getText() : 'NO TRANSLATION';
}
```

and my formbuilder

```
    $formMapper
        ->add('label')
        ->add('translations', 'a2lix_translations', [
            'locales' => $countryHelper->getCountryList(),
            'fields' => [
                'text' => [
                    'field_type' => 'textarea',
                    'label' => 'description',
                    'attr' => [
                        'class' => 'tinymce',
                    ],
                ],
            ]
        ])
    ;
```

and here the content of the getContryList method

```
Array
(
    [0] => en
    [1] => fr
    [2] => es
)
```

...

```
doctrine:
orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    filters:
        oneLocale:
            class: A2lix\I18nDoctrineBundle\Doctrine\ORM\Filter\OneLocaleFilter
            enabled: true
```

...

```
a2lix_i18n_doctrine:
    manager_registry: doctrine
```
